In [6]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.6.28-cp314-cp314-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: tqdm in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.6 MB 320.3 kB/s eta 0:00:04
   ------------- -------------------------- 0.5/1.6 MB 320.3 kB/s eta 0:00:04
   ------------- -------------------------- 0.5/1.6 MB 320.3 kB/s eta 0:00:04
   ------------- -------------------------- 0.5/1.6 MB 320.3 kB/s eta 0:00:04
   -------------------- ------------------- 0.8/1.6 MB 320.0 kB/s eta 0:00:03
   -------------------- ------------------- 0.8/1.6 MB 320.0 kB/s eta 0:00:03
   -------------------- ------------------- 0.8/1.6 MB 320.0 kB/s eta 0:00:03
   --------------------------- ------------ 1.0/1.6 MB 326.5 kB/s eta 0:00:02
   --------------------------- ------------ 1.0/1.6 MB 326.5 kB/s eta 0:00:02
   --------------------------------- ------ 1.3/1.6 MB 383.7 kB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 383.7 kB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 398.3 kB/s  0:00:04
Downloading regex-2026.6.28-cp314-cp314-win_amd64.whl (280 kB)
Installing collected packages: regex, nltk

   ---------------------------------------- 0/2 [regex]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   ---------------------------------------- 2/2 [nltk]

Successfully installed nltk-3.9.4 regex-2026.6.28
Note: you may need to restart the kernel to use updated packages.

In [7]:
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (3.9.4)
Requirement already satisfied: click in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from nltk) (2026.6.28)
Requirement already satisfied: tqdm in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in C:\Users\user\AppData\Roaming\Python\Python314\site-packages (from click->nltk) (0.4.6)

In [8]:
import pandas as pd
import numpy as np

import re
import string

import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

import warnings
warnings.filterwarnings("ignore")

In [9]:
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...

True

In [10]:
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [11]:
df = pd.read_csv("../data/processed/eda_completed.csv")

df.head()

,idd,title,text,label,text_length,word_count
0,Fq+C96tcx+,‘A target on Roe v. Wade ’: Oklahoma bill maki...,UPDATE: Gov. Fallin vetoed the bill on Friday....,REAL,6677,1088
1,bHUqK!pgmv,Study: women had to drive 4 times farther afte...,Ever since Texas laws closed about half of the...,REAL,4044,692
2,4Y4Ubf%aTi,"Trump, Clinton clash in dueling DC speeches","Donald Trump and Hillary Clinton, now at the s...",REAL,3274,520
3,_CoY89SJ@K,Grand jury in Texas indicts activists behind P...,A Houston grand jury investigating criminal al...,REAL,5316,813
4,+rJHoRQVLe,"As Reproductive Rights Hang In The Balance, De...",WASHINGTON -- Forty-three years after the Supr...,REAL,2660,430

In [12]:
df = df[["title","text","label"]]

df.head()

,title,text,label
0,‘A target on Roe v. Wade ’: Oklahoma bill maki...,UPDATE: Gov. Fallin vetoed the bill on Friday....,REAL
1,Study: women had to drive 4 times farther afte...,Ever since Texas laws closed about half of the...,REAL
2,"Trump, Clinton clash in dueling DC speeches","Donald Trump and Hillary Clinton, now at the s...",REAL
3,Grand jury in Texas indicts activists behind P...,A Houston grand jury investigating criminal al...,REAL
4,"As Reproductive Rights Hang In The Balance, De...",WASHINGTON -- Forty-three years after the Supr...,REAL

In [13]:
df["content"] = df["title"] + " " + df["text"]

df.head()

,title,text,label,content
0,‘A target on Roe v. Wade ’: Oklahoma bill maki...,UPDATE: Gov. Fallin vetoed the bill on Friday....,REAL,‘A target on Roe v. Wade ’: Oklahoma bill maki...
1,Study: women had to drive 4 times farther afte...,Ever since Texas laws closed about half of the...,REAL,Study: women had to drive 4 times farther afte...
2,"Trump, Clinton clash in dueling DC speeches","Donald Trump and Hillary Clinton, now at the s...",REAL,"Trump, Clinton clash in dueling DC speeches Do..."
3,Grand jury in Texas indicts activists behind P...,A Houston grand jury investigating criminal al...,REAL,Grand jury in Texas indicts activists behind P...
4,"As Reproductive Rights Hang In The Balance, De...",WASHINGTON -- Forty-three years after the Supr...,REAL,"As Reproductive Rights Hang In The Balance, De..."

In [14]:
df["content"] = df["content"].str.lower()

df.head()

,title,text,label,content
0,‘A target on Roe v. Wade ’: Oklahoma bill maki...,UPDATE: Gov. Fallin vetoed the bill on Friday....,REAL,‘a target on roe v. wade ’: oklahoma bill maki...
1,Study: women had to drive 4 times farther afte...,Ever since Texas laws closed about half of the...,REAL,study: women had to drive 4 times farther afte...
2,"Trump, Clinton clash in dueling DC speeches","Donald Trump and Hillary Clinton, now at the s...",REAL,"trump, clinton clash in dueling dc speeches do..."
3,Grand jury in Texas indicts activists behind P...,A Houston grand jury investigating criminal al...,REAL,grand jury in texas indicts activists behind p...
4,"As Reproductive Rights Hang In The Balance, De...",WASHINGTON -- Forty-three years after the Supr...,REAL,"as reproductive rights hang in the balance, de..."

In [15]:
def remove_html(text):
    clean = re.compile("<.*?>")
    return re.sub(clean, "", text)

In [16]:
df["content"] = df["content"].apply(remove_html)

In [17]:
def remove_url(text):
    return re.sub(r"https?://\S+|www\.\S+", "", text)

In [18]:
df["content"] = df["content"].apply(remove_url)

In [19]:
def remove_numbers(text):
    return re.sub(r"\d+", "", text)

In [20]:
df["content"] = df["content"].apply(remove_numbers)

In [21]:
def remove_punctuation(text):
    return text.translate(
        str.maketrans("", "", string.punctuation)
    )

In [22]:
df["content"] = df["content"].apply(remove_punctuation)

In [23]:
def remove_spaces(text):
    return " ".join(text.split())

In [24]:
df["content"] = df["content"].apply(remove_spaces)

In [25]:
def remove_special(text):
    return re.sub(r"[^a-zA-Z\s]", "", text)

In [26]:
df["content"] = df["content"].apply(remove_special)

In [27]:
df["tokens"] = df["content"].apply(word_tokenize)

df.head()

,title,text,label,content,tokens
0,‘A target on Roe v. Wade ’: Oklahoma bill maki...,UPDATE: Gov. Fallin vetoed the bill on Friday....,REAL,a target on roe v wade oklahoma bill making i...,"[a, target, on, roe, v, wade, oklahoma, bill, ..."
1,Study: women had to drive 4 times farther afte...,Ever since Texas laws closed about half of the...,REAL,study women had to drive times farther after t...,"[study, women, had, to, drive, times, farther,..."
2,"Trump, Clinton clash in dueling DC speeches","Donald Trump and Hillary Clinton, now at the s...",REAL,trump clinton clash in dueling dc speeches don...,"[trump, clinton, clash, in, dueling, dc, speec..."
3,Grand jury in Texas indicts activists behind P...,A Houston grand jury investigating criminal al...,REAL,grand jury in texas indicts activists behind p...,"[grand, jury, in, texas, indicts, activists, b..."
4,"As Reproductive Rights Hang In The Balance, De...",WASHINGTON -- Forty-three years after the Supr...,REAL,as reproductive rights hang in the balance deb...,"[as, reproductive, rights, hang, in, the, bala..."

In [28]:
stop_words = set(stopwords.words("english"))

In [29]:
def remove_stopwords(tokens):
    return [
        word
        for word in tokens
        if word not in stop_words
    ]

In [30]:
df["tokens"] = df["tokens"].apply(remove_stopwords)

In [31]:
stemmer = PorterStemmer()

In [32]:
def stemming(tokens):
    return [
        stemmer.stem(word)
        for word in tokens
    ]

In [33]:
df["stemmed"] = df["tokens"].apply(stemming)

In [34]:
lemmatizer = WordNetLemmatizer()

In [35]:
def lemmatization(tokens):
    return [
        lemmatizer.lemmatize(word)
        for word in tokens
    ]

In [36]:
df["lemmatized"] = df["tokens"].apply(lemmatization)

In [37]:
df["clean_text"] = df["lemmatized"].apply(
    lambda x: " ".join(x)
)

df.head()

,title,text,label,content,tokens,stemmed,lemmatized,clean_text
0,‘A target on Roe v. Wade ’: Oklahoma bill maki...,UPDATE: Gov. Fallin vetoed the bill on Friday....,REAL,a target on roe v wade oklahoma bill making i...,"[target, roe, v, wade, oklahoma, bill, making,...","[target, roe, v, wade, oklahoma, bill, make, f...","[target, roe, v, wade, oklahoma, bill, making,...",target roe v wade oklahoma bill making felony ...
1,Study: women had to drive 4 times farther afte...,Ever since Texas laws closed about half of the...,REAL,study women had to drive times farther after t...,"[study, women, drive, times, farther, texas, l...","[studi, women, drive, time, farther, texa, law...","[study, woman, drive, time, farther, texas, la...",study woman drive time farther texas law close...
2,"Trump, Clinton clash in dueling DC speeches","Donald Trump and Hillary Clinton, now at the s...",REAL,trump clinton clash in dueling dc speeches don...,"[trump, clinton, clash, dueling, dc, speeches,...","[trump, clinton, clash, duel, dc, speech, dona...","[trump, clinton, clash, dueling, dc, speech, d...",trump clinton clash dueling dc speech donald t...
3,Grand jury in Texas indicts activists behind P...,A Houston grand jury investigating criminal al...,REAL,grand jury in texas indicts activists behind p...,"[grand, jury, texas, indicts, activists, behin...","[grand, juri, texa, indict, activist, behind, ...","[grand, jury, texas, indicts, activist, behind...",grand jury texas indicts activist behind plann...
4,"As Reproductive Rights Hang In The Balance, De...",WASHINGTON -- Forty-three years after the Supr...,REAL,as reproductive rights hang in the balance deb...,"[reproductive, rights, hang, balance, debate, ...","[reproduct, right, hang, balanc, debat, moder,...","[reproductive, right, hang, balance, debate, m...",reproductive right hang balance debate moderat...

In [38]:
print("Original Text\n")
print(df.loc[0,"text"])

print("\n"+"="*100+"\n")

print("Clean Text\n")
print(df.loc[0,"clean_text"])

Original Text

UPDATE: Gov. Fallin vetoed the bill on Friday. Head here for more.

Lawmakers in Oklahoma approved a bill Thursday that would make performing abortions a felony and revoke the medical licenses of most physicians who assist in such procedures.

This sweeping measure, which opponents described as unconstitutional and unprecedented, now heads to Gov. Mary Fallin (R). She will have five days — not including Sunday — to decide whether to sign the bill, veto it or allow it to become law without her signature, according to a spokesman.

“The governor will withhold comment on that bill, as she does on most bills, until she and her staff have had a chance to review it,” Michael McNutt, a spokesman for Fallin, said in an email.

The Oklahoma bill is the first such measure of its kind, according to the Center for Reproductive Rights, which says that other states seeking to ban abortion have simply banned the procedure rather than attaching penalties like this.

According to the measure, known as SB1552, a person who performs or induces an abortion will be guilty of a felony and punished with between one and three years in the state penitentiary.

This legislation also says that any physician who participates in an abortion — deemed “unprofessional conduct” in the bill — will be “prohibited from obtaining or renewing a license to practice medicine in this state.” However, medical licenses will not be stripped from doctors who perform abortions deemed necessary to save the mother’s life.

[Yes, hospitals perform abortions. This D.C. doctor says her hospital won’t let her talk about it]

The bill passed the Oklahoma House of Representatives with a vote of 59-to-9 last month. On Thursday, the state’s senate passed it with a vote of 33-to-12.

“Since I believe life begins at conception, it should be protected, and I believe it’s a core function of state government to defend that life from the beginning of conception,” State Sen. Nathan Dahm, a Republican who represents Tulsa County, told the Associated Press.

Dahm said he hopes the Oklahoma measure could eventually lead to the overturning of Roe v. Wade, the 1973 Supreme Court decision that recognized a woman’s right to an abortion. Dahm did not respond to messages seeking comment Thursday and Friday.

Dawn Laguens, executive vice president of Planned Parenthood Federation of America,  said last month that the Oklahoma bill is “a ban on abortion, plain and simple.” The legislation sent to Fallin on Thursday “is reckless and dangerous,” according to Ilyse Hogue, president of NARAL Pro-Choice America.

“This bill puts doctors in the cross hairs for providing women with the option of exercising our fundamental right to decide how and when to start a family,” Hogue said in a statement. “And it creates penalties for doctors doing their jobs: performing a safe and legal medical procedure.”

Liberty Counsel, a group that rose to national prominence last year defending the Kentucky clerk who refused to sign same-sex marriage licenses, said Friday that it had helped support the legislation in Oklahoma. The organization also vowed to defend it in court.

“This particular bill puts a target on Roe v. Wade,” Mat Staver, the group’s founder and chairman, said in an interview Friday. “It is Oklahoma’s line in the sand on the sanctity of human life, as standing on the side of protecting innocent children.”

Staver said that his group met with Oklahoma lawmakers before the legislation was filed, offering legal analysis after discussions had begun in the state about proposing such a measure.

The Oklahoma bill is “the first of its kind,” Staver said, though he said it was possible other states may follow Oklahoma’s lead.

“This is a bolt step in the right direction, in my view,” Staver said. “It will be challenged and we’re prepared to defend it.”

[Oklahoma isn’t the only state taking big steps to limit abortions]

The Oklahoma State Medical Association, which has called the measure “troubling,” has said it would not take a position on the legality of abortion as long as the practice remains legal. However, the group said it was opposed to “legislation that is designed to intimidate physicians or override their medical judgment.”

On Thursday, the group reiterated that opposition, calling it “one more insulting slap in the face of our state’s medical providers” and urging Fallin to veto the legislation.

“We are extremely disappointed in today’s vote,” Sherri Baker, president of the medical association, said in a statement Thursday. “It is simply unconscionable that, at a time when our state already faces a severe physician shortage, the senate would waste its time on a bill that is patently unconstitutional and whose only purposes are to score political points and intimidate physicians across this state.”

When the measure was debated in the state’s House of Representatives, a legislator who ultimately voted against the bill pointed to the group’s opposition and voiced concerns that the law could lead to doctors abandoning Oklahoma. But one of the bill’s co-sponsors said he did not think it would have an impact.

Since taking office in 2011, Fallin has signed more than a dozen bills restricting access to reproductive health care, the Center for Reproductive Rights, a nonprofit legal group, said Thursday.

The new bill “is blatantly unconstitutional and, if it takes effect, it will be the most extreme abortion law in this country” since the Roe v. Wade decision, Amanda Allen, senior state legislative counsel at the center, wrote in a letter to Fallin on Thursday.

Allen said her group was urging Fallin to veto the legislation, which she said was part of a larger pattern of lawmakers in the state chipping away at abortion rights.

“Policymakers in Oklahoma should focus on advancing policies that will truly promote women’s health and safety, not abortion restrictions that do just the opposite,” Allen wrote. “Anti-choice politicians in the state have methodically restricted access to abortion and neglected to advance policies that truly address the challenges women and families face every day.”

Allen also said that the bill would “almost certainly lead to expensive court challenges that the state of Oklahoma simply cannot defend in light of longstanding Supreme Court precedent.”

Fallin has until next week to make a decision on the bill. If this measure does become law, it would go into effect on Nov. 1.

The forgotten history of Justice Ginsburg’s criticism of Roe v. Wade

Indiana banned abortions if fetuses have Down syndrome

This story, first published on Thursday, has been updated on Friday to include Liberty Counsel’s comments.

====================================================================================================

Clean Text

target roe v wade oklahoma bill making felony perform abortion wait governor decision update gov fallin vetoed bill friday head lawmaker oklahoma approved bill thursday would make performing abortion felony revoke medical license physician assist procedure sweeping measure opponent described unconstitutional unprecedented head gov mary fallin r five day including sunday decide whether sign bill veto allow become law without signature according spokesman governor withhold comment bill bill staff chance review michael mcnutt spokesman fallin said email oklahoma bill first measure kind according center reproductive right say state seeking ban abortion simply banned procedure rather attaching penalty like according measure known sb person performs induces abortion guilty felony punished one three year state penitentiary legislation also say physician participates abortion deemed unprofessional conduct bill prohibited obtaining renewing license practice medicine state however medical license stripped doctor perform abortion deemed necessary save mother life yes hospital perform abortion dc doctor say hospital wont let talk bill passed oklahoma house representative vote last month thursday state senate passed vote since believe life begin conception protected believe core function state government defend life beginning conception state sen nathan dahm republican represents tulsa county told associated press dahm said hope oklahoma measure could eventually lead overturning roe v wade supreme court decision recognized woman right abortion dahm respond message seeking comment thursday friday dawn laguens executive vice president planned parenthood federation america said last month oklahoma bill ban abortion plain simple legislation sent fallin thursday reckless dangerous according ilyse hogue president naral prochoice america bill put doctor cross hair providing woman option exercising fundamental right decide start family hogue said statement creates penalty doctor job performing safe legal medical procedure liberty counsel group rose national prominence last year defending kentucky clerk refused sign samesex marriage license said friday helped support legislation oklahoma organization also vowed defend court particular bill put target roe v wade mat staver group founder chairman said interview friday oklahoma line sand sanctity human life standing side protecting innocent child staver said group met oklahoma lawmaker legislation filed offering legal analysis discussion begun state proposing measure oklahoma bill first kind staver said though said possible state may follow oklahoma lead bolt step right direction view staver said challenged prepared defend oklahoma isnt state taking big step limit abortion oklahoma state medical association called measure troubling said would take position legality abortion long practice remains legal however group said opposed legislation designed intimidate physician override medical judgment thursday group reiterated opposition calling one insulting slap face state medical provider urging fallin veto legislation extremely disappointed today vote sherri baker president medical association said statement thursday simply unconscionable time state already face severe physician shortage senate would waste time bill patently unconstitutional whose purpose score political point intimidate physician across state measure debated state house representative legislator ultimately voted bill pointed group opposition voiced concern law could lead doctor abandoning oklahoma one bill cosponsors said think would impact since taking office fallin signed dozen bill restricting access reproductive health care center reproductive right nonprofit legal group said thursday new bill blatantly unconstitutional take effect extreme abortion law country since roe v wade decision amanda allen senior state legislative counsel center wrote letter fallin thursday allen said group urging fallin veto legislation said part larger pattern lawmaker state chipping away abortion right policymakers oklahoma focus advancing policy truly promote womens health safety abortion restriction opposite allen wrote antichoice politician state methodically restricted access abortion neglected advance policy truly address challenge woman family face every day allen also said bill would almost certainly lead expensive court challenge state oklahoma simply defend light longstanding supreme court precedent fallin next week make decision bill measure become law would go effect nov forgotten history justice ginsburgs criticism roe v wade indiana banned abortion fetus syndrome story first published thursday updated friday include liberty counsel comment

In [39]:
df.isnull().sum()

title         0
text          0
label         0
content       0
tokens        0
stemmed       0
lemmatized    0
clean_text    0
dtype: int64

In [40]:
df[["clean_text","label"]].head()

                                          clean_text label
0  target roe v wade oklahoma bill making felony ...  REAL
1  study woman drive time farther texas law close...  REAL
2  trump clinton clash dueling dc speech donald t...  REAL
3  grand jury texas indicts activist behind plann...  REAL
4  reproductive right hang balance debate moderat...  REAL

In [41]:
df.to_csv(
    "../data/processed/preprocessed_data.csv",
    index=False
)

In [42]:
print("="*60)
print("Text Preprocessing Completed Successfully")
print("="*60)

print("Total Samples :", len(df))

print("Columns :", df.columns.tolist())

print("Missing Values :", df.isnull().sum().sum())

============================================================
Text Preprocessing Completed Successfully
============================================================
Total Samples : 4593
Columns : ['title', 'text', 'label', 'content', 'tokens', 'stemmed', 'lemmatized', 'clean_text']
Missing Values : 0